save-position-on-quit
sub-font-size=66
sub-border-size=4


[erased]
aid=1
sub-auto=fuzzy
sub-file-paths=subs.ja:subs.en
slang=ja,en
sid=auto
secondary-sid=auto
sub-font-size=38
secondary-sub-pos=6

# mpv --profile=erased 'Erased - 01.mkv'


[bakemonogatari]
aid=1
sub-auto=fuzzy
sub-file-paths=subs.jp:subs.en
slang=ja,en
sid=auto
secondary-sid=auto
secondary-sub-pos=6

# mpv --profile=bakemonogatari 'Bakemonogatari 01 - Hitagi Crab, Part 1.mkv'


[sonny-boy]
aid=2
sub-auto=fuzzy
sub-file-paths=subs.jp:subs.en
slang=ja,en
sid=auto
secondary-sid=auto
secondary-sub-pos=6

# mpv --profile=sonny-boy 'Sonny Boy - 01 - The Island At The Far End Of Summer.mkv'


[wonder-egg-priority]
aid=2
sub-auto=fuzzy
sub-file-paths=subs.jp:subs.en
slang=ja,en
sid=auto
secondary-sid=auto
secondary-sub-pos=6

# mpv --profile=wonder-egg-priority 'Wonder Egg Priority - S01E01 - The Domain Of Children.mkv'


[fullmetal-alchemist]
aid=2
sub-visibility=yes
sub-auto=fuzzy
sub-file-paths=subs.jp:subs.en
slang=ja,en
sid=auto
secondary-sid=auto
secondary-sub-pos=6

# mpv --profile=fullmetal-alchemist 'Fullmetal_Alchemist 01 - He Who Would Challenge the Sun.mkv'
