save-position-on-quit
sub-font-size=66
sub-border-size=4


# slang=ja,ja-JP,jp
# sub-ass-force-style=ScaledBorderAndShadow=yes
# sub-border-color="#000000"
# sub-border-size=10
# sub-color="#FFFFFFFF"
# sub-font-size=48
# sub-margin-y=36
# sub-shadow-color="#000000"
# sub-shadow-offset=2
